paths:
  output_dir : output/synonyms/result/
  input_dir : output/synonyms/eval/
  wrong_dir : output/synonyms/result/wrong/
  result_dir : output/synonyms/result/summary/
  eval_dir : output/synonyms/result/eval/
  delta_dir : output/synonyms/result/delta/

suffixes:
  wrong1 : .wrong1
  wrong2 : .wrong2
  wrong3 : .wrong3
  result1 : .result1
  result2 : .result2
  result3 : .result3
  eval1 : .eval1
  eval2 : .eval2
  eval3 : .eval3
  delta1 : .delta1
  delta2 : .delta2
  delta3 : .delta3

test_evaluation_type:
  1 : eval_type1
  9 : eval_type7
